// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: customer.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer(
    id,
    username,
	password,
	first_name,
	last_name,
	address,
	email,
	phone_number,
	active,
	create_at,
	update_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, username, password, first_name, last_name, address, email, phone_number, active, create_at, update_at
`

type CreateCustomerParams struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Password    sql.NullString `json:"password"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Address     sql.NullString `json:"address"`
	Email       sql.NullString `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Active      sql.NullBool   `json:"active"`
	CreateAt    sql.NullTime   `json:"create_at"`
	UpdateAt    sql.NullTime   `json:"update_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Address,
		arg.Email,
		arg.PhoneNumber,
		arg.Active,
		arg.CreateAt,
		arg.UpdateAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Email,
		&i.PhoneNumber,
		&i.Active,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getCustomerInfoByUsername = `-- name: GetCustomerInfoByUsername :many
SELECT id, username, password, first_name, last_name, address, email, phone_number, active, create_at, update_at from customer
WHERE
    username=$1
`

func (q *Queries) GetCustomerInfoByUsername(ctx context.Context, username string) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerInfoByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Address,
			&i.Email,
			&i.PhoneNumber,
			&i.Active,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customer
SET 
	username=$2,
	first_name=$3,
	last_name=$4,
	address=$5,
	email = $6,
	phone_number = $7
WHERE
	id=$1
RETURNING id, username, password, first_name, last_name, address, email, phone_number, active, create_at, update_at
`

type UpdateCustomerParams struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Address     sql.NullString `json:"address"`
	Email       sql.NullString `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Address,
		arg.Email,
		arg.PhoneNumber,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Address,
		&i.Email,
		&i.PhoneNumber,
		&i.Active,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
